import json
import requests
from bs4 import BeautifulSoup

POST_LOGO = "https://www.washingtonpost.com/touch-icon-iphone-retina.png"
BOOKS = ["https://www.washingtonpost.com/entertainment/books/fiction/",
         "https://www.washingtonpost.com/entertainment/books/nonfiction/"]


def lambda_handler(event, context):
    return get_json_feed(False)


def sorter(el):
    return el["date_published"]


def get_json_feed(debug):
    feed_items = []
    c = 0
    for url in BOOKS:
        c += 1
        print("GET " + url)
        page = requests.get(url)
        page_soup = BeautifulSoup(page.content, 'html.parser')
        print("Parsed")

        post_data_soup = page_soup.find("script", {"id": "__NEXT_DATA__"})
        post_data = json.loads(post_data_soup.text)
        if debug:
            post_file = open("post_" + str(c) + ".json", "w")
            post_file.write(json.dumps(post_data, indent=2))
            post_file.close()

        items = post_data["props"]["pageProps"]["globalContent"]["items"]
        print("Post Data Items " + str(len(items)))
        for item in items:
            article_id = item["_id"]
            article_url = item["canonical_url"]
            article_title = item["headlines"]["basic"]
            print(article_title)
            article_date = item["first_publish_date"]
            article_body = item["description"]["basic"]
            article_image = item["additional_properties"]["lead_art"]["additional_properties"]["thumbnailResizeUrl"]
            article_author = item["credits"]["by"][0]["name"]

            feed_article = {
                'id': article_id,
                'title': article_title,
                'authors': [{'name': article_author}],
                'url': article_url,
                'content_text': article_body,
                'date_published': article_date,
                'image': article_image,
            }
            feed_items.append(feed_article)

    feed = {
        'version': 'https://jsonfeed.org/version/1.1',
        'title': 'Washington Post Books',
        'home_page_url': "https://www.washingtonpost.com/entertainment/books/",
        'user_comment': 'Generated by https://github.com/prenagha/washingtonpost-books-jsonfeed',
        'icon': POST_LOGO,
        'favicon': POST_LOGO,
        'items': sorted(feed_items, key=sorter, reverse=True)
    }
    return json.dumps(feed, indent=2)


if __name__ == '__main__':
    feed_str = get_json_feed(True)
    feed_file = open("feed.json", "w")
    feed_file.write(feed_str)
    feed_file.close()
