import datetime
import json
import requests
from bs4 import BeautifulSoup

POST_LOGO = "https://www.washingtonpost.com/touch-icon-iphone-retina.png"
FICTION = "https://www.washingtonpost.com/entertainment/books/fiction/"


def lambda_handler(event, context):
    return get_json_feed(False)


def get_json_feed(debug):
    url = FICTION
    print("GET " + url)
    page = requests.get(url)
    page_soup = BeautifulSoup(page.content, 'html.parser')
    print("Parsed")

    post_data = page_soup.find("script", {"id": "__NEXT_DATA__"})
    if debug:
        post_file = open("post.json", "w")
        post_file.write(json.dumps(json.loads(post_data.text), indent=2))
        post_file.close()
        exit(9)

    feed_items = []
    for article in page_soup.find('article').find_all('div', {'class': 'story-headline'}):
        kicker = article.find('div', {'data-qa': 'kicker'})
        if not kicker or kicker.text != 'Review':
            continue
        anchor = article.find('a')
        article_url = anchor.get(key='href')
        article_title = anchor.text.strip()
        print("Item " + article_title + article_url)
        dt = article.find('span', {'data-testid': 'timestamp'}).text.strip()
        article_date = datetime.datetime.strptime(dt, "%B %d, %Y").isoformat()
        article_body = article.find('p').text.strip()

        article_image = POST_LOGO
        print("looking for img for " + article_url)
        for link in page_soup.find_all('a', {'href': article_url}):
            img = link.find("img")
            if img:
                article_image = img.get("src")
                print(" found an image in link " + article_image)
                break
            else:
                print(" found a link NO IMAGE " + str(link))

        break
        article_author = "Washington Post"
        for span in article.find_all('span'):
            txt = span.text.strip()
            if txt.startswith("By "):
                article_author = txt.removeprefix("By ")
                break

        feed_article = {
            'id': article_url,
            'title': article_title,
            'authors': [{'name': article_author}],
            'url': article_url,
            'content_text': article_body,
            'date_published': article_date,
            'image': article_image,
        }
        feed_items.append(feed_article)

    feed = {
        'version': 'https://jsonfeed.org/version/1.1',
        'title': 'Washington Post Books',
        'home_page_url': "https://www.washingtonpost.com/entertainment/books/",
        'user_comment': 'Generated by https://github.com/prenagha/washingtonpost-books-jsonfeed',
        'icon': POST_LOGO,
        'favicon': POST_LOGO,
        'items': feed_items
    }
    return json.dumps(feed, indent=2)


if __name__ == '__main__':
    feed_str = get_json_feed(True)
    feed_file = open("feed.json", "w")
    feed_file.write(feed_str)
    feed_file.close()
